apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress-default
  annotations:
    # nginx.ingress.kubernetes.io/rewrite-target: /$1
    # add an annotation indicating the issuer to use.
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: letsencrypt-production
    nginx.ingress.kubernetes.io/proxy-body-size: 8m
    #ingress.kubernetes.io/ssl-redirect: "true" 
    #ingress.kubernetes.io/secure-backends: "true"    
    #ingress.kubernetes.io/force-ssl-redirect: "true"
    kubernetes.io/ingress.allow-http: "false"
spec:
  backend:
    serviceName: backend-service
    servicePort: 8080
  #rules:
  #- host: {{.Values.domainName}}
  #  http:
  #    paths:
  #    - path: /|/(.+)
  #      backend:
  #        serviceName: backend-service
  #        servicePort: 8080
  # Ingress-shim will automatically create a cert
  # when a host is placed in the TLS config
  tls:
  - hosts:
    - {{.Values.domainName}}
    # cert-manager will store the created certificate in this secret.
    secretName: ingress-default-cert
